# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b761fd93cbbf1693c404c110bd0455fca20488fe6782d47194899bc4252b27af2c1e22889e3e47f631667bcffd7840cffe416af94571ec15a0157778a6f5251

test:
  secret_key_base: ee8e9a087330b5d8a99eef04aafacde126eb5b007109680522440f98f1c5c165e842ebbfbc8d65489c5036770fbad0cde4608f5f442d0948cff62f0cc61a6e44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
